name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths: ["Dockerfile", "airsensor.c"]
    tags:
      - '*'
  schedule:
    - cron: '0 0 28 * *'

permissions:
  contents: read

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      -
        name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@4574d27a4764455b42196d70a065bc6853246a25 # v3.4.0
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3.9.0
      -
        name: Login to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - if: github.ref == 'refs/heads/main'
        name: Conditional(Set tag as `latest`)
        run: echo "tag=volschin/airsensor:latest" >> $GITHUB_ENV

      - if: startsWith(github.ref, 'refs/tags/')
        name: Conditional(Set tag as `{version}`)
        run: echo "tag=volschin/airsensor:${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      -
        name: Build and push
        uses: docker/build-push-action@0adf9959216b96bec444f325f1e493d4aa344497 # v6.14.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            ${{ env.tag }}
